"""Add custom_study_plans table

Revision ID: 3de8f1003e81
Revises: 
Create Date: 2025-11-04 23:18:00.308511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de8f1003e81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # 1. Agregar audio_url solo si no existe
    columns = [col['name'] for col in inspector.get_columns('documents')]
    if 'audio_url' not in columns:
        op.add_column('documents', sa.Column('audio_url', sa.String(), nullable=True))
    
    # 2. Crear tabla custom_study_plans solo si no existe
    existing_tables = inspector.get_table_names()
    if 'custom_study_plans' not in existing_tables:
        op.create_table('custom_study_plans',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('title', sa.String(length=200), nullable=False),
            sa.Column('level', sa.String(length=50), nullable=False),
            sa.Column('content', sa.JSON(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('document_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    
    # 3. Modificar time_taken solo si es necesario
    try:
        op.alter_column('quiz_attempts', 'time_taken',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    except Exception:
        pass
    
    # 4. Eliminar constraint solo si existe
    constraints = [c['name'] for c in inspector.get_unique_constraints('subjects')]
    if 'subjects_name_key' in constraints:
        op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Eliminar tabla si existe
    existing_tables = inspector.get_table_names()
    if 'custom_study_plans' in existing_tables:
        op.drop_table('custom_study_plans')
    
    # Restaurar constraint si no existe
    constraints = [c['name'] for c in inspector.get_unique_constraints('subjects')]
    if 'subjects_name_key' not in constraints:
        op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
        
    # Revertir time_taken
    try:
        op.alter_column('quiz_attempts', 'time_taken',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    except Exception:
        pass
    
    # Eliminar audio_url si existe
    columns = [col['name'] for col in inspector.get_columns('documents')]
    if 'audio_url' in columns:
        op.drop_column('documents', 'audio_url')
    # ### end Alembic commands ###
