"""Add custom_study_plans table

Revision ID: 3de8f1003e81
Revises: 
Create Date: 2025-11-04 23:18:00.308511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de8f1003e81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('audio_url', sa.String(), nullable=True))
    op.alter_column('quiz_attempts', 'time_taken',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
    op.alter_column('quiz_attempts', 'time_taken',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'audio_url')
    # ### end Alembic commands ###
