"""Add custom_study_plans table

Revision ID: 3de8f1003e81
Revises: 
Create Date: 2025-11-04 23:18:00.308511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de8f1003e81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar audio_url solo si no existe
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('documents')]
    
    if 'audio_url' not in columns:
        op.add_column('documents', sa.Column('audio_url', sa.String(), nullable=True))
    
    # Crear tabla custom_study_plans (coincidir exactamente con models.py)
    op.create_table('custom_study_plans',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('level', sa.String(length=50), nullable=False),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.alter_column('quiz_attempts', 'time_taken',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # Eliminar constraint solo si existe
    try:
        op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    except:
        pass  # Si no existe, continuar
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_study_plans')
    
    try:
        op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
    except:
        pass
        
    op.alter_column('quiz_attempts', 'time_taken',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    # Solo eliminar audio_url si existe
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('documents')]
    
    if 'audio_url' in columns:
        op.drop_column('documents', 'audio_url')
    # ### end Alembic commands ###
