"""add refactor custom_plans 

Revision ID: 45586e9cbe96
Revises: 3de8f1003e81
Create Date: 2025-11-04 23:32:58.510552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45586e9cbe96'
down_revision: Union[str, None] = '3de8f1003e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Esta migración ya no es necesaria, la tabla se crea correctamente en la anterior
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
